### ISSUE TITLE
Paypal Error - License Purchase

### ISSUE THREAD

**Issue by eli876** [keshavbhatt/WonderWall-Packaging#1]
Unable to purchase license. Paypal site doesn't load the security challenge.

**Comment by keshavbhatt** [comment]
Hi, sorry for the inconvenience. Can you confirm the installation method you used to install the application? 
For now the workaround is to click the "copy payment url" button that appears at the bottom of the payment page and opening it in a web browser to make payment. 

I will fix the issue in next update.

**Comment by eli876** [comment]
Thanks for the response.
I was able to purchase the lifetime key. Fantastic app!

**Comment by keshavbhatt** [comment]
The issue has been resolved in the latest update(build#389) of Wonderwall.
