### ISSUE TITLE
Wallpaper set error!

### ISSUE THREAD

**Issue by Joker2770** [keshavbhatt/WonderWall-Packaging#2]
![2021-11-04 09-39-39屏幕截图](https://user-images.githubusercontent.com/22749204/140244710-6cee9729-63b4-4f13-b8dd-e6999ed6a399.png)

**Comment by Joker2770** [comment]
~~~
xxxx:~$ echo $DESKTOP_SESSION 
xfce

~~~

**Comment by keshavbhatt** [comment]
How you installed Wonderwall on your system?

**Comment by Joker2770** [comment]
> How you installed Wonderwall on your system?

sudo snap install wonderwall

**Comment by keshavbhatt** [comment]
I never tested xfce backend with snap install, I doubt it may not work since the calls won't be able to exit the snap confinement. Hence, I request you to use AppImage. Sorry for the inconvenience.

**Comment by Joker2770** [comment]
> I never tested xfce backend with snap install, I doubt it may not work since the calls won't be able to exit the snap confinement. Hence, I request you to use AppImage. Sorry for the inconvenience.

thanks for your explaination.
