### ISSUE TITLE
Linux/Windows versions suddenly don't work.

### ISSUE THREAD

**Issue by Astralogic** [keshavbhatt/WonderWall-Packaging#3]
The program worked fine a week ago, now it fails to load any images. It seems it can't connect to the net or something, it loads forever. The same issue is experienced no matter the version of wonderwall whether it be linux or windows. I've tried the snap, the flatpak, the appimage, and I compiled it from the AUR.

It seems to be just broken now. I often get the "Aww crap, something exploded" error message and "unable to connect to source".

**Comment by keshavbhatt** [comment]
The issue will be fixed shorty. Sorry for the inconvinience.

**Comment by keshavbhatt** [comment]
If the issue has been fixed, feel free to close the ticket.
